from pathlib import Path
import pygame

BASE_DIR = Path(__file__).parent
ASSETS_DIR = BASE_DIR / "Assets"

MAP_PATH = ASSETS_DIR / "maps" / "level_1.tmx"
BACKGROUND_PATH = ASSETS_DIR / "Background" / "background.jpg"

CHARACTER_BASE = ASSETS_DIR / "Characters" / "Caveman"

WINDOW_SIZE = (1280, 720)
WINDOW_TITLE = "GRID SURVIVAL"
BACKGROUND_COLOR = (18, 18, 22)
TARGET_FPS = 60

PLAYER_FRAME_DURATION = 1 / 24
PLAYER_SCALE = 0.2
PLAYER_START_POS = (WINDOW_SIZE[0] // 2, WINDOW_SIZE[1] // 2)
PLAYER_SPEED = 200
PLAYER_DEFAULT_DIRECTION = "down"
PLAYER_FALL_GRAVITY = 800
PLAYER_FALL_MAX_SPEED = 1000
PLAYER_SINK_SPEED = 80

# Jump mechanics
PLAYER_JUMP_VELOCITY = -400  # Initial upward velocity
PLAYER_JUMP_GRAVITY = 1200  # Gravity during jump
PLAYER_MAX_FALL_SPEED = 600  # Terminal velocity during jump
PLAYER_JUMP_KEY = pygame.K_SPACE  # Default jump key

PLAYER_ANIMATION_PATHS = {
	"idle": {
		"down": CHARACTER_BASE / "idle" / "Front - Idle Blinking",
		"up": CHARACTER_BASE / "idle" / "Back - Idle",
		"left": CHARACTER_BASE / "idle" / "Left - Idle Blinking",
		"right": CHARACTER_BASE / "idle" / "Right - Idle Blinking",
	},
	"run": {
		"down": CHARACTER_BASE / "running" / "Front - Running",
		"up": CHARACTER_BASE / "running" / "Back - Running",
		"left": CHARACTER_BASE / "running" / "Left - Running",
		"right": CHARACTER_BASE / "running" / "Right - Running",
	},
	"death": {
		"down": CHARACTER_BASE / "Dying",
		"up": CHARACTER_BASE / "Dying",
		"left": CHARACTER_BASE / "Dying",
		"right": CHARACTER_BASE / "Dying",
	},
}

WALKABLE_LAYER_NAMES = ["Top"]
WALKABLE_OBJECT_CLASS_NAMES = ["Platform"]
WALKABLE_ISO_TOP_FRACTION = 1

DEBUG_VISUALS_ENABLED = False
DEBUG_DRAW_WALKABLE = True
DEBUG_WALKABLE_COLOR = (30, 144, 255)
DEBUG_DRAW_PLAYER_FOOTBOX = True
DEBUG_PLAYER_FOOTBOX_COLOR = (255, 230, 0)

WATER_SPRITESHEET = ASSETS_DIR / "Background" / "Water" / "Animated Water.png"
WATER_FRAME_SIZE = (192, 96)
WATER_FRAME_COUNT = 24
WATER_FRAME_DURATION = 1 / 12
WATER_TARGET_HEIGHT = 150
WATER_SPLASH_SPRITESHEET = (
	ASSETS_DIR / "Background" / "Water" / "Animated Water-Splash-Sheet-192x1344.png"
)
WATER_SPLASH_FRAME_SIZE = (192, 192)
WATER_SPLASH_FRAME_COUNT = 7
WATER_SPLASH_FRAME_DURATION = 1 / 18
WATER_SPLASH_SIZE = (256, 256)

USE_AI_PLAYER = True
AI_DECISION_INTERVAL = 0.22
AI_LOOKAHEAD_DISTANCE = 42
AI_EDGE_MARGIN_WEIGHT = 0.06

# Opening scene audio
MUSIC_PATH = BASE_DIR / "Soundtrack" / "TileSuv2.mp3"
MUSIC_VOLUME = 0.45

# Opening scenes visual constants
TITLE_TEXT = "TILE SURVIVAL"
TITLE_FONT_SIZE = 96
TITLE_SUB_FONT_SIZE = 34
INPUT_FONT_SIZE = 36
WARNING_FONT_SIZE = 28
MODE_HEADER_FONT_SIZE = 64
MODE_SUBTITLE_FONT_SIZE = 34
MODE_CARD_TITLE_SIZE = 36
MODE_CARD_DESC_SIZE = 24

TITLE_PARTICLE_COUNT = 90
TITLE_PARTICLE_MIN_SIZE = 6
TITLE_PARTICLE_MAX_SIZE = 16
TITLE_PARTICLE_MIN_SPEED = 20
TITLE_PARTICLE_MAX_SPEED = 70

NAME_MAX_LENGTH = 16
INPUT_BOX_WIDTH = 500
INPUT_BOX_HEIGHT = 62
MODE_CARD_WIDTH = 700
MODE_CARD_HEIGHT = 110
MODE_CARD_SPACING = 132

SCENE_FADE_SPEED = 420  # alpha units per second
TITLE_DROP_DURATION = 0.85
TITLE_PULSE_SPEED = 3.2
PROMPT_BLINK_SPEED = 2.0
MODE_CLICK_FLASH_TIME = 0.15

TITLE_BG_COLOR = (12, 15, 28)
TITLE_SUBTITLE_COLOR = (220, 230, 250)
INPUT_LABEL_COLOR = (245, 245, 255)
INPUT_BOX_BG_COLOR = (28, 36, 58)
INPUT_BOX_BORDER_COLOR = (245, 185, 70)
INPUT_TEXT_COLOR = (255, 255, 255)
PROMPT_TEXT_COLOR = (255, 220, 90)
WARNING_TEXT_COLOR = (255, 70, 70)

MODE_BG_COLOR = (10, 14, 26)
MODE_HEADER_COLOR = (255, 230, 120)
MODE_SUBTITLE_COLOR = (220, 228, 255)
MODE_CARD_BASE_COLOR = (32, 44, 68)
MODE_CARD_HOVER_COLOR = (58, 86, 128)
MODE_CARD_BORDER_COLOR = (230, 190, 80)
MODE_CARD_TITLE_COLOR = (255, 255, 255)
MODE_CARD_DESC_COLOR = (210, 220, 235)
MODE_CARD_CLICK_BASE = (90, 110, 50)
TITLE_PARTICLE_COLOR_BASE = (255, 180, 60)
SCENE_OVERLAY_COLOR = (0, 0, 0)

TITLE_COLORS = [
	(255, 70, 70),
	(255, 140, 40),
	(255, 220, 60),
]

MODE_VS_COMPUTER = "vs_computer"
MODE_LOCAL_MULTIPLAYER = "local_multiplayer"
MODE_ONLINE_MULTIPLAYER = "online_multiplayer"
